# Generated by Django 4.0 on 2022-04-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renderer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomaly',
            name='id',
            field=models.FloatField(primary_key=True, serialize=False),
        ),
    ]
