# Generated by Django 4.0 on 2022-04-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renderer', '0002_alter_anomaly_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detector',
            name='id',
            field=models.FloatField(primary_key=True, serialize=False),
        ),
    ]
