# Generated by Django 4.0 on 2022-04-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renderer', '0003_alter_detector_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomaly',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detector',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
