# Generated by Django 4.0 on 2022-04-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renderer', '0004_alter_anomaly_id_alter_detector_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomaly',
            name='center_x',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='center_y',
            field=models.FloatField(blank=True),
        ),
    ]
