# Generated by Django 4.0 on 2022-04-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renderer', '0006_alter_anomaly_center_x_alter_anomaly_center_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomaly',
            name='real_rate',
            field=models.FloatField(null=True),
        ),
    ]
